title: Green Jekyll Site
description: A simple Jekyll site with green theme.
baseurl: ""
url: "https://cfcbermuda.github.io"
permalink: /:title/
future: true # Enable future-dated posts
theme: null # Disable default theme
defaults:
  - scope:
      path: ""
    values:
      layout: "default"